"""sync models

Revision ID: 01e418b3b130
Revises: dbd56bdc5b34
Create Date: 2026-01-11 18:00:44.813232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01e418b3b130'
down_revision = 'dbd56bdc5b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('product_installed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('full_name')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('product_installed')
        batch_op.drop_column('booking_time')

    # ### end Alembic commands ###
