"""Add booking details columns

Revision ID: 44fa791e54ac
Revises: 1a44c6e5c4e3
Create Date: 2026-01-11 14:32:32.343575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44fa791e54ac'
down_revision = '1a44c6e5c4e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('product_installed', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('additional_info', sa.Text(), nullable=True))
    # ### end Alembic commands ###

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('additional_info')
        batch_op.drop_column('product_installed')
        batch_op.drop_column('booking_time')

    # ### end Alembic commands ###
