"""Add public_id to users

Revision ID: a7557681205c
Revises: cd1fa09871a8
Create Date: 2026-01-12 10:19:43.838133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7557681205c'
down_revision = 'cd1fa09871a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_user_public_id'), ['public_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_public_id'))
        batch_op.drop_column('public_id')

    # ### end Alembic commands ###
