"""Add latest_energy_calculation to User

Revision ID: cd1fa09871a8
Revises: 01e418b3b130
Create Date: 2026-01-12 09:43:46.925894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1fa09871a8'
down_revision = '01e418b3b130'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latest_energy_calculation', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('latest_energy_calculation')

    # ### end Alembic commands ###
